before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq php5-gmp

language: php

php:
  - 5.4
  - 5.5

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit --coverage-text
